### ISSUE TITLE
Put I2C support in-tree

### ISSUE THREAD

**Issue by JDuchniewicz** [Willmish/bibop-zephyr-eos-s3#15]
Currently there is no in-tree support for Zephyr's I2C for EOS S3. 

Steps to do so include:
- [x] Add new file for i2c using HAL
- [x] Use antmicro's HAL or update the HAL hosted on zephyr-rtos repository
- [x] Use Wishbone HAL as well
- [x] Use I2C driver from Zephyr for reading sensor data

**Comment by Willmish** [comment]
Current HAL: https://github.com/Willmish/hal_quicklogic/tree/hal_i2c

Current Zephyr fork with fixes: https://github.com/Willmish/zephyr/tree/eos_s3_fixes

**Comment by Willmish** [comment]
bang, done (for now, may need to refactor it): https://github.com/Willmish/zephyr/commit/777e5809c1a7aea781ab25d1af9559e9d17098ea
